@echo off
REM Show WAS environment settings
echo WAS_ROOT = %WAS_ROOT%
echo MY_WAS_NODE = %MY_WAS_NODE%
echo MY_SP_ID_08 = %MY_SP_ID_08%
echo MY_SP_PASSWORD_08 = %MY_SP_PASSWORD_08%
echo MY_SP_ID_23 = %MY_SP_ID_23%
echo MY_SP_PASSWORD_23 = %MY_SP_PASSWORD_23%
echo WAS_PROFILE_NAME = %WAS_PROFILE_NAME%
echo WAS_PROFILE_SERVER_NAME = %WAS_PROFILE_SERVER_NAME%
echo WAS_ADMIN_USER = %WAS_ADMIN_USER%
echo WAS_ADMIN_PASSWORD = %WAS_ADMIN_PASSWORD%
echo DATABASE_PATH = %DATABASE_PATH% 